### ISSUE TITLE
需要依赖TensorFlow吗？

### ISSUE THREAD

**Issue by kaerweinuo** [ownthink/Jiagu#10]
Failed to load the native TensorFlow runtime.

**Comment by ownthink** [comment]
需要依赖TensorFlow和numpy的，可以直接用pip3 install jiagu，或者clone代码然后python3 setup.py install ，会自动安装TensorFlow和numpy。

**Comment by kaerweinuo** [comment]
> 需要依赖TensorFlow和numpy的，可以直接用pip3 install jiagu，或者clone代码然后python3 setup.py install ，会自动安装TensorFlow和numpy。


Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_impor
t_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\imp.py
", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\imp.py
", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "index.py", line 1, in <module>
    import jiagu
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\jiagu\__init__.py", line 3, in <module>
    from jiagu import analyze
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\jiagu\analyze.py", line 13, in <module>
    from jiagu import bilstm_crf
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\jiagu\bilstm_crf.py", line 7, in <module>
    import tensorflow as tf
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_impor
t_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\imp.py
", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\imp.py
", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ownthink** [comment]
import tensorflow as tf  会报错吗

**Comment by kaerweinuo** [comment]
> import tensorflow as tf 会报错吗

import tensorflow as tf  会报错

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_impor
t_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\imp.py
", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\imp.py
", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "t.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_impor
t_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\imp.py
", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\imp.py
", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ownthink** [comment]
@kaerweinuo 可以重新安装下tensorflow的
