### ISSUE TITLE
python ERROR

### ISSUE THREAD

**Issue by laughter8** [ownthink/Jiagu#31]
test code:
···
import jiagu
text = "今天又是新的一天"
words = jiagu.seg(text)
print(words)
···
[ERROR]:
python jiagu_test.py
Traceback (most recent call last):
  File "jiagu_test.py", line 1, in <module>
    import jiagu
  File "/anaconda3/envs/jiguangENV/lib/python3.5/site-packages/jiagu/__init__.py", line 11, in <module>
    from jiagu import analyze
  File "/anaconda3/envs/jiguangENV/lib/python3.5/site-packages/jiagu/analyze.py", line 14, in <module>
    from jiagu import bilstm_crf
  File "/anaconda3/envs/jiguangENV/lib/python3.5/site-packages/jiagu/bilstm_crf.py", line 16, in <module>
    from tensorflow.contrib.crf import viterbi_decode
ImportError: No module named 'tensorflow.contrib'

--------------------
应该是TensorFlow版本的问题，请问下TensorFlow版本是多少是可以用的；或者有没有requirements.txt可以参考一下~

**Comment by ownthink** [comment]
tensorflow最近更新到2.0了，还没进行兼容，目前建议先使用tensorflow 1.6


------------------
郑文裕


 




------------------ 原始邮件 ------------------
发件人: "laughter8"<notifications@github.com>;
发送时间: 2019年10月16日(星期三) 中午11:22
收件人: "ownthink/Jiagu"<Jiagu@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [ownthink/Jiagu] python ERROR (#31)




test code:
 ···
 import jiagu
 text = "今天又是新的一天"
 words = jiagu.seg(text)
 print(words)
 ···
 [ERROR]:
 python jiagu_test.py
 Traceback (most recent call last):
 File "jiagu_test.py", line 1, in 
 import jiagu
 File "/anaconda3/envs/jiguangENV/lib/python3.5/site-packages/jiagu/init.py", line 11, in 
 from jiagu import analyze
 File "/anaconda3/envs/jiguangENV/lib/python3.5/site-packages/jiagu/analyze.py", line 14, in 
 from jiagu import bilstm_crf
 File "/anaconda3/envs/jiguangENV/lib/python3.5/site-packages/jiagu/bilstm_crf.py", line 16, in 
 from tensorflow.contrib.crf import viterbi_decode
 ImportError: No module named 'tensorflow.contrib'
 
 
应该是TensorFlow版本的问题，请问下TensorFlow版本是多少是可以用的；或者有没有requirements.txt可以参考一下~

**Comment by laughter8** [comment]
1.6可以用，感谢~
