### ISSUE TITLE
import报错

### ISSUE THREAD

**Issue by HanZhang-LiXin** [ownthink/Jiagu#60]
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import jiagu
  File "/apsara/TempRoot/Odps/hm_tech_dev_20200831122729601g98ujyup2_198b4bb4_338b_4f5a_aab0_f6e84abbd9cb_AlgoTask_0_0/tensorflow@bd011089190037.na63#0/venv/lib/python2.7/site-packages/jiagu/__init__.py", line 3, in <module>
    from jiagu import analyze
  File "/apsara/TempRoot/Odps/hm_tech_dev_20200831122729601g98ujyup2_198b4bb4_338b_4f5a_aab0_f6e84abbd9cb_AlgoTask_0_0/tensorflow@bd011089190037.na63#0/venv/lib/python2.7/site-packages/jiagu/analyze.py", line 9, in <module>
    from jiagu.segment.nroute import Segment
ImportError: No module named segment.nroute

**Comment by ownthink** [comment]
仅支持python&nbsp;3.0哦


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: HanZhang-LiXin <notifications@github.com&gt;
发送时间: 2020年8月31日 20:32
收件人: ownthink/Jiagu <Jiagu@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[ownthink/Jiagu] import报错 (#60)





 
Traceback (most recent call last):
 File "main.py", line 2, in 
 import jiagu
 File "/apsara/TempRoot/Odps/hm_tech_dev_20200831122729601g98ujyup2_198b4bb4_338b_4f5a_aab0_f6e84abbd9cb_AlgoTask_0_0/tensorflow@bd011089190037.na63#0/venv/lib/python2.7/site-packages/jiagu/init.py", line 3, in 
 from jiagu import analyze
 File "/apsara/TempRoot/Odps/hm_tech_dev_20200831122729601g98ujyup2_198b4bb4_338b_4f5a_aab0_f6e84abbd9cb_AlgoTask_0_0/tensorflow@bd011089190037.na63#0/venv/lib/python2.7/site-packages/jiagu/analyze.py", line 9, in 
 from jiagu.segment.nroute import Segment
 ImportError: No module named segment.nroute
